# Generated by Django 4.2.4 on 2023-10-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_app', '0002_userprofile_bch_userprofile_btc_userprofile_eth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoin',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='usercoin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='coin',
        ),
        migrations.AddField(
            model_name='transaction',
            name='coin_ticker',
            field=models.CharField(default='btc', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bch',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='eth',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ltc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xrp',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
        migrations.DeleteModel(
            name='UserCoin',
        ),
    ]
